### ISSUE TITLE
E-board connection type change causes problem

### ISSUE THREAD

**Issue by osparking** [osparking/OsParking#3]
When E-board connection type changed to RS-232(from TCP/IP), it caused two problems;
1. Panel graphic breaks as shown below.
   ![1st row, right-hand side](https://github.com/osparking/OsParking/blob/master/images/errors/e-board-panel-break.jpg)
2. java.lang.NumberFormatException: For input string: ""
   Originated from --
	at com.osparking.osparking.Settings_System.changeTCP_VS_COM(Settings_System.java:4573)
	at com.osparking.osparking.Settings_System.E_Board1_connTypeCBoxItemStateChanged(Settings_System.java:3201)
	at com.osparking.osparking.Settings_System.access$2600(Settings_System.java:199)
	at com.osparking.osparking.Settings_System$23.itemStateChanged(Settings_System.java:1172)
Please take this into account!

**Comment by osparking** [comment]
Problem fixed by setting COM1 by default. Details follow--

Related commit : 2cf72043bafba38bab5058e96decdb750884c4d9

[Details]
Cause of the problem:
As soon as a device connection type is set to RS-232, an event handler
displays a combo box to display and/or accept the COM port ID for the device. 
The handler would also tries to select one item of the combo box referring 
parking lot database.
However, when COM_ID field is not initialized in the database, 
the handler fails to make initial box item selection and the problem happens.

Solution:
In case COM_ID field is not initialized in the database, the event handler is
changed to choose the first item of the combo box which is COM1.
