### ISSUE TITLE
Runtime error after database restored.

### ISSUE THREAD

**Issue by osparking** [osparking/OsParking#30]
Exception in thread "ospConnect_E_Board_1_timer" java.lang.ClassCastException: com.osparking.osparking.device.EBoardManager cannot be cast to com.osparking.global.names.IDevice$ISerial
	at com.osparking.osparking.device.ConnectDeviceTask.run(ConnectDeviceTask.java:101)
	at com.osparking.global.names.ParkingTimer$5.run(ParkingTimer.java:123)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by osparking** [comment]
The problem occurs when the device simulator managers are forced to be casted to ISerial interface.
However, simulator managers don't implement ISerial.  They implement ISocket interface.
So, problem is solved by forcing the connection type of device simulator to be TCP/IP socket only.

Additionally, "hardware port not found warning dialog" changed a bit, too.
These fixes appear on 1bef2c1e8be4057a49059bce837afc51bf1df921.
